// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SquirrelTracker.Models;

#nullable disable

namespace SquirrelTracker.Migrations
{
    [DbContext(typeof(SquirrelDbContext))]
    partial class SquirrelDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SquirrelTracker.Models.Items.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A crunchy oak nut packed with energy — perfect for winter storage.",
                            Name = "Acorn"
                        },
                        new
                        {
                            Id = 2,
                            Description = "A scaly pine treasure filled with hidden seeds inside.",
                            Name = "Pinecone"
                        },
                        new
                        {
                            Id = 3,
                            Description = "A tough shell but worth the effort for the rich nut inside.",
                            Name = "Walnut"
                        },
                        new
                        {
                            Id = 4,
                            Description = "A light, twirling seed that’s easy to carry and snack on.",
                            Name = "Maple Seed"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Smooth and shiny — a favorite autumn treat for any squirrel.",
                            Name = "Chestnut"
                        },
                        new
                        {
                            Id = 6,
                            Description = "A colorful assortment of forest berries, sweet and juicy.",
                            Name = "Berry Mix"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Soft and savory, found under the shade of tall trees.",
                            Name = "Mushroom Cap"
                        },
                        new
                        {
                            Id = 8,
                            Description = "A small round nut with a mild, buttery flavor.",
                            Name = "Hazelnut"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Dried golden kernels, crunchy and filling for long trips.",
                            Name = "Corn Kernel"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Tiny but full of flavor and fat — a top choice for energy.",
                            Name = "Sunflower Seed"
                        });
                });

            modelBuilder.Entity("SquirrelTracker.Models.Squirrels.Squirrel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.ToTable("Squirrels");
                });

            modelBuilder.Entity("SquirrelTracker.Models.StashLines.StashLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("StashId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("StashId", "ItemId")
                        .IsUnique();

                    b.ToTable("StashLines");
                });

            modelBuilder.Entity("SquirrelTracker.Models.Stashes.Stash", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("SquirrelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SquirrelId");

                    b.ToTable("Stashes");
                });

            modelBuilder.Entity("SquirrelTracker.Models.StashLines.StashLine", b =>
                {
                    b.HasOne("SquirrelTracker.Models.Items.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SquirrelTracker.Models.Stashes.Stash", "Stash")
                        .WithMany("StashLines")
                        .HasForeignKey("StashId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Stash");
                });

            modelBuilder.Entity("SquirrelTracker.Models.Stashes.Stash", b =>
                {
                    b.HasOne("SquirrelTracker.Models.Squirrels.Squirrel", "Squirrel")
                        .WithMany("StashList")
                        .HasForeignKey("SquirrelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Squirrel");
                });

            modelBuilder.Entity("SquirrelTracker.Models.Squirrels.Squirrel", b =>
                {
                    b.Navigation("StashList");
                });

            modelBuilder.Entity("SquirrelTracker.Models.Stashes.Stash", b =>
                {
                    b.Navigation("StashLines");
                });
#pragma warning restore 612, 618
        }
    }
}
